name = "news-discord"
main = "src/entry.py"
compatibility_date = "2025-04-01"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "discord-news-db"
database_id = ""

[triggers]
crons = ["0 21-23 * * 0-4", "30 21-23 * * 0-4", "0 0-9 * * 1-5", "30 0-9 * * 1-5"]
