name = "news-discord"
main = "src/entry.py"
compatibility_date = "2025-04-01"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "discord-news-db"
database_id = ""

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["5 23 * * *"]
